# Generated by Django 4.2 on 2023-11-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='trim',
            field=models.CharField(default='Base', max_length=30),
        ),
    ]
