# Generated by Django 4.2 on 2023-11-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_accessory_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'verbose_name': 'Accessory', 'verbose_name_plural': 'Accessories'},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'verbose_name': 'Maintenance', 'verbose_name_plural': 'Maintenance'},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vin_number',
            field=models.CharField(default='', max_length=17),
        ),
    ]
