# Generated by Django 4.2 on 2023-12-06 15:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0006_accessory_date_updated_maintenance_date_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriesfile',
            name='date_entered',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='accessoriesfile',
            name='date_updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesfile',
            name='entered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancefile',
            name='date_entered',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='maintenancefile',
            name='date_updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancefile',
            name='entered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
