# Generated by Django 4.2 on 2023-12-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_alter_accessoriesfile_date_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessoriesfile',
            old_name='date_entered',
            new_name='entered_date',
        ),
        migrations.RenameField(
            model_name='accessory',
            old_name='date_entered',
            new_name='entered_date',
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='date_entered',
            new_name='entered_date',
        ),
        migrations.RenameField(
            model_name='maintenancefile',
            old_name='date_entered',
            new_name='entered_date',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='date_entered',
            new_name='entered_date',
        ),
        migrations.RemoveField(
            model_name='accessoriesfile',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='maintenancefile',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='accessoriesfile',
            name='entered_time',
            field=models.TimeField(blank=True, default='11:40:20', null=True),
        ),
        migrations.AddField(
            model_name='accessoriesfile',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesfile',
            name='updated_time',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='entered_time',
            field=models.TimeField(blank=True, default='11:40:20', null=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='updated_time',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='entered_time',
            field=models.TimeField(blank=True, default='11:40:20', null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='updated_time',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancefile',
            name='entered_time',
            field=models.TimeField(blank=True, default='11:40:20', null=True),
        ),
        migrations.AddField(
            model_name='maintenancefile',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancefile',
            name='updated_time',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='entered_time',
            field=models.TimeField(blank=True, default='11:40:20', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
