# Generated by Django 4.2 on 2025-05-21 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_alter_maintenance_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessoriesfile',
            old_name='accessory',
            new_name='fk_accessory_id',
        ),
        migrations.RenameField(
            model_name='accessoriesfile',
            old_name='vehicle',
            new_name='fk_vehicle_id',
        ),
        migrations.RenameField(
            model_name='accessory',
            old_name='vehicle',
            new_name='fk_vehicle_id',
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='category',
            new_name='fk_category_id',
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='vehicle',
            new_name='fk_vehicle_id',
        ),
        migrations.RenameField(
            model_name='maintenancefile',
            old_name='maintenance',
            new_name='fk_maintenance_id',
        ),
        migrations.RenameField(
            model_name='vehicleregistration',
            old_name='vehicle',
            new_name='fk_vehicle_id',
        ),
    ]
