# Generated by Django 4.2 on 2025-05-21 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('error_logging', '0005_remove_stacktrace_error_id_stacktrace_error_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='error',
            old_name='user',
            new_name='fk_user_id',
        ),
        migrations.RenameField(
            model_name='stacktrace',
            old_name='error_fk',
            new_name='fk_error_id',
        ),
    ]
