# Generated by Django 4.2 on 2025-05-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
