# Generated by Django 4.2 on 2023-11-17 04:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import apps.services.maintenance.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0002_vehicle_trim'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancefile',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=apps.services.maintenance.models.maintenance_file_upload_path),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='trim',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('short_description', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('purchased_from', models.CharField(blank=True, max_length=50, null=True)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('date_entered', models.DateField(default=datetime.datetime.now)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='AccessoriesFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='uploads/accessories/')),
                ('accessory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.accessory')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.vehicle')),
            ],
        ),
    ]
