# Generated by Django 4.2 on 2023-11-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_vehicle_description_alter_maintenancefile_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Still Own?'),
        ),
    ]
