# Generated by Django 4.2 on 2024-07-15 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='short_description',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.category'),
        ),
    ]
