# Generated by Django 4.2 on 2024-07-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0014_alter_category_options_maintenance_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='short_description',
            field=models.CharField(default='', max_length=50),
        ),
    ]
