# Generated by Django 4.2 on 2025-05-26 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0002_alter_category_options'),
        ('maintenance', '0017_alter_vehicle_entered_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancefile',
            name='entered_by',
        ),
        migrations.RemoveField(
            model_name='maintenancefile',
            name='fk_maintenance_id',
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='entered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='fk_category_id',
            field=models.ForeignKey(limit_choices_to={'app_laber': 'maintenance'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.category'),
        ),
        migrations.DeleteModel(
            name='AccessoriesFile',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='MaintenanceFile',
        ),
    ]
