# Generated by Django 4.2 on 2025-10-07 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_category_options_alter_condition_options_and_more'),
        ('maintenance', '0018_remove_maintenancefile_entered_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='fk_category_id',
            field=models.ForeignKey(limit_choices_to={'app_label': 'maintenance'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.category'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
