# Generated by Django 4.2 on 2025-12-28 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0019_alter_maintenance_fk_category_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('vehicle', 'Vehicle'), ('home', 'Home'), ('system', 'System'), ('appliance', 'Appliance')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_entered_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_entered_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('interval_miles', models.PositiveIntegerField(blank=True, null=True)),
                ('reminder', models.BooleanField(default=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='maintenance.asset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='last_updated_date',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='last_updated_time',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='last_updated_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='last_updated_time',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date_entered',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='entered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_entered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='date_entered',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='TaskConsumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.consumable')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenancetask')),
            ],
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='consumables',
            field=models.ManyToManyField(blank=True, related_name='tasks', through='maintenance.TaskConsumable', to='maintenance.consumable'),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='entered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_entered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessory',
            name='fk_asset',
            field=models.ForeignKey(blank=True, limit_choices_to={'asset_type': 'vehicle'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.asset'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.asset'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.maintenancetask'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fk_asset',
            field=models.OneToOneField(blank=True, limit_choices_to={'asset_type': 'vehicle'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='maintenance.asset'),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='fk_asset',
            field=models.ForeignKey(blank=True, limit_choices_to={'asset_type': 'vehicle'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.asset'),
        ),
    ]
