# Generated by Django 4.2 on 2025-12-28 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0020_asset_consumable_maintenancetask_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='fk_vehicle_id',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='fk_vehicle_id',
        ),
        migrations.RemoveField(
            model_name='vehicleregistration',
            name='fk_vehicle_id',
        ),
    ]
