# Generated by Django 4.2 on 2025-12-28 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_subcategory_console'),
        ('maintenance', '0021_remove_accessory_fk_vehicle_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='fk_category_id',
            field=models.ForeignKey(blank=True, limit_choices_to={'app_label': 'maintenance'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.category'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_performed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
