# Generated by Django 4.2 on 2025-12-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0022_alter_maintenance_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetask',
            name='due',
            field=models.BooleanField(default=True),
        ),
    ]
