# Generated by Django 4.2 on 2025-12-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0023_maintenancetask_due'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancetask',
            old_name='due',
            new_name='due_now',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
