# Generated by Django 4.2 on 2025-12-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0024_rename_due_maintenancetask_due_now_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumable',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
