# Generated by Django 4.2 on 2025-12-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0025_alter_consumable_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='current_mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mileage_this_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='starting_mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
