# Generated by Django 4.2 on 2025-12-29 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0026_vehicle_current_mileage_vehicle_mileage_this_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='next_service_date',
        ),
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.IntegerField()),
                ('fk_asset', models.ForeignKey(blank=True, limit_choices_to={'asset_type': 'vehicle'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mileage', to='maintenance.asset')),
            ],
        ),
    ]
