# Generated by Django 4.2 on 2025-12-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0027_remove_maintenance_next_service_date_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='current_mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='installed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='manual_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='model_identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='serial_num',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial/VIN'),
        ),
        migrations.AddField(
            model_name='asset',
            name='starting_mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_expires',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='mileage',
            index=models.Index(fields=['fk_asset', 'mileage'], name='maintenance_fk_asse_640dc0_idx'),
        ),
    ]
