# Generated by Django 4.2 on 2025-12-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0028_asset_current_mileage_asset_installed_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
