# Generated by Django 4.2 on 2025-12-30 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0029_delete_vehicle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumable',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='consumable',
            name='fk_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumable', to='maintenance.asset'),
        ),
    ]
