# Generated by Django 4.2 on 2026-01-01 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0030_alter_consumable_options_consumable_fk_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='consumable',
            name='fk_asset',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='fk_category_id',
        ),
        migrations.AlterField(
            model_name='accessory',
            name='fk_asset',
            field=models.ForeignKey(blank=True, limit_choices_to={'asset_type': 'vehicle'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='maintenance.asset'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maintenance.asset'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maintenance.maintenancetask'),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='maintenance.asset'),
        ),
        migrations.AlterField(
            model_name='taskconsumable',
            name='consumable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.consumable'),
        ),
        migrations.AlterField(
            model_name='taskconsumable',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.maintenancetask'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('fk_asset_type', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='maintenance.assettype', verbose_name='Asset Type')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'fk_asset_type')},
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='fk_asset_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset', to='maintenance.assettype', verbose_name='Asset Type'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='fk_category',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumables', to='maintenance.category'),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='fk_category',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='maintenance.category', verbose_name='Category'),
        ),
    ]
