# Generated by Django 4.2 on 2026-01-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0032_alter_mileage_options_mileage_date_entered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetask',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
