# Generated by Django 4.2 on 2026-01-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0033_maintenancetask_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskconsumable',
            name='quantity',
            field=models.FloatField(default=1),
        ),
    ]
