# Generated by Django 4.2 on 2025-05-21 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('error_logging', '0004_stacktrace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stacktrace',
            name='error_id',
        ),
        migrations.AddField(
            model_name='stacktrace',
            name='error_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_fk', to='error_logging.error'),
        ),
    ]
