# Generated by Django 4.2 on 2025-02-26 00:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DKIM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField(blank=True, max_length=100, null=True)),
                ('org', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('extra_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('report_id', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('adkim', models.CharField(blank=True, max_length=1, null=True)),
                ('aspf', models.CharField(blank=True, max_length=1, null=True)),
                ('dkim_policy', models.CharField(blank=True, max_length=10, null=True)),
                ('date_entered', models.DateField(default=datetime.datetime.now)),
                ('last_updated_date', models.DateField(auto_now=True, null=True)),
                ('last_updated_time', models.TimeField(auto_now=True, null=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dkim_entered_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dkim_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_dkim',
            },
        ),
        migrations.CreateModel(
            name='DKIM_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('record_type', models.CharField(blank=True, max_length=10, null=True)),
                ('domain', models.TextField(blank=True, max_length=100, null=True)),
                ('selector', models.CharField(blank=True, max_length=100, null=True)),
                ('result', models.BooleanField(default=False)),
                ('date_entered', models.DateField(default=datetime.datetime.now)),
                ('last_updated_date', models.DateField(auto_now=True, null=True)),
                ('last_updated_time', models.TimeField(auto_now=True, null=True)),
                ('dkim_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dkim_record', to='email_mgt.dkim')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dkim_record_entered_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dkim_record_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_dkim_record',
            },
        ),
    ]
