# Generated by Django 4.2 on 2025-03-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_mgt', '0002_alter_dkim_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dkim',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
