# Generated by Django 4.2 on 2025-05-29 00:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_manageddevice_agent_version_manageddevice_cpu_cores_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entered', models.DateField(default=datetime.datetime.now)),
                ('last_updated_date', models.DateField(auto_now=True, null=True)),
                ('last_updated_time', models.TimeField(auto_now=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ram_used_mb', models.IntegerField(blank=True, null=True)),
                ('disk_free_gb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disk_used_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('net_recv_mb', models.FloatField(blank=True, null=True)),
                ('net_sent_mb', models.FloatField(blank=True, null=True)),
                ('uptime', models.CharField(blank=True, max_length=50, null=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_entered_by', to=settings.AUTH_USER_MODEL)),
                ('fk_device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='devices.manageddevice')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entered', models.DateField(default=datetime.datetime.now)),
                ('last_updated_date', models.DateField(auto_now=True, null=True)),
                ('last_updated_time', models.TimeField(auto_now=True, null=True)),
                ('alert_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_entered_by', to=settings.AUTH_USER_MODEL)),
                ('fk_device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='devices.manageddevice')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonitoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entered', models.DateField(default=datetime.datetime.now)),
                ('last_updated_date', models.DateField(auto_now=True, null=True)),
                ('last_updated_time', models.TimeField(auto_now=True, null=True)),
                ('brute_force_monitoring', models.BooleanField(default=False)),
                ('package_checking', models.BooleanField(default=False)),
                ('interval', models.IntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_entered_by', to=settings.AUTH_USER_MODEL)),
                ('fk_device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='devices.manageddevice')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManualCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(max_length=50)),
                ('result_summary', models.TextField()),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('fk_device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.manageddevice')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
