# Generated by Django 4.2 on 2025-05-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoringconfig',
            name='interval',
        ),
        migrations.AddField(
            model_name='monitoringconfig',
            name='brute_force_interval',
            field=models.IntegerField(default=60, help_text='How often should you check failed logins?'),
        ),
        migrations.AddField(
            model_name='monitoringconfig',
            name='is_alive_interval',
            field=models.IntegerField(default=60, help_text='How often should you check if the server is online?'),
        ),
        migrations.AddField(
            model_name='monitoringconfig',
            name='package_interval',
            field=models.IntegerField(default=1440, help_text='How often should you check if the server has package updates?'),
        ),
    ]
