# Generated by Django 4.2 on 2025-05-20 23:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=50)),
                ('web_address', models.CharField(max_length=150)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_vue_app', models.BooleanField(default=False)),
                ('login_required', models.BooleanField(default=False)),
                ('is_monitoring', models.BooleanField(default=False)),
                ('ip_address', models.CharField(blank=True, max_length=15, null=True)),
                ('monitoring_port', models.IntegerField(blank=True, default=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManagedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('os', models.CharField(choices=[('Windows', 'Windows'), ('Linux', 'Linux'), ('MacOS', 'MacOS')], max_length=20)),
                ('device_type', models.CharField(choices=[('yubikey', 'YubiKey'), ('pc', 'PC'), ('server', 'Server')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_virtual', models.BooleanField(default=False)),
                ('has_keys', models.BooleanField(default=False)),
                ('date_entered', models.DateField(default=datetime.datetime.now)),
                ('last_updated_date', models.DateField(auto_now=True, null=True)),
                ('last_updated_time', models.TimeField(auto_now=True, null=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_entered', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SshKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('public_key', models.TextField()),
                ('key_type', models.CharField(choices=[('ed25519 ', 'ed25519 '), ('rsa', 'RSA')])),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('date_entered', models.DateField(default=datetime.datetime.now)),
                ('last_updated_date', models.DateField(auto_now=True, null=True)),
                ('last_updated_time', models.TimeField(auto_now=True, null=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssh_entered', to=settings.AUTH_USER_MODEL)),
                ('fk_device_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.manageddevice')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssh_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=15, null=True)),
                ('host_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_cores', models.IntegerField(blank=True, null=True)),
                ('cpu_sockets', models.IntegerField(blank=True, null=True)),
                ('cpu_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disc_space', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disc_space_free', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disc_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('network_recv', models.FloatField()),
                ('network_sent', models.FloatField()),
                ('uptime', models.CharField(max_length=25)),
                ('date_entered', models.DateField(default=datetime.datetime.now)),
                ('last_updated_date', models.DateField(auto_now=True, null=True)),
                ('last_updated_time', models.TimeField(auto_now=True, null=True)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.app')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitors_entered', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitors_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
