# Generated by Django 4.2 on 2023-04-24 17:34

import apps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=50)),
                ('web_address', models.CharField(max_length=150)),
                ('icon', models.ImageField(upload_to=apps.models.upload_image)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
