# Generated by Django 4.2 on 2023-04-24 17:36

import apps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=apps.models.upload_image),
        ),
    ]
