# Generated by Django 4.2 on 2023-04-25 23:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_app_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
