# Generated by Django 4.2 on 2023-11-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_app_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='loggin_required',
            field=models.BooleanField(default=False),
        ),
    ]
