# Generated by Django 4.2 on 2025-05-21 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0004_alter_manageddevice_device_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageddevice',
            name='fk_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
