# Generated by Django 4.2 on 2023-11-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_app_loggin_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='is_vue_app',
            field=models.BooleanField(default=False),
        ),
    ]
