# Generated by Django 4.2 on 2023-11-11 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_app_is_vue_app'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='loggin_required',
            new_name='login_required',
        ),
    ]
