# Generated by Django 4.2 on 2024-07-21 23:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0007_rename_loggin_required_app_login_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='ip_address',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='is_monitoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='app',
            name='monitoring_port',
            field=models.IntegerField(blank=True, default=5000, null=True),
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=15, null=True)),
                ('host_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_cores', models.IntegerField(blank=True, null=True)),
                ('cpu_sockets', models.IntegerField(blank=True, null=True)),
                ('cpu_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disc_space', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disc_space_free', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disc_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('network_recv', models.FloatField()),
                ('network_sent', models.FloatField()),
                ('uptime', models.CharField(max_length=25)),
                ('date_entered', models.DateField(default=datetime.datetime.now)),
                ('last_updated_date', models.DateField(auto_now=True, null=True)),
                ('last_updated_time', models.TimeField(auto_now=True, null=True)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.app')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitors_entered', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitors_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
