# Generated by Django 4.2 on 2024-07-23 16:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0008_app_ip_address_app_is_monitoring_app_monitoring_port_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Monitor',
            new_name='ServerStatus',
        ),
    ]
