# Generated by Django 4.2 on 2025-05-07 20:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0010_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('os', models.CharField(choices=[('MacOS', 'MacOS'), ('Windows', 'Windows'), ('Linux', 'Linux')], max_length=20)),
                ('device_type', models.CharField(choices=[('pc', 'PC'), ('server', 'Server')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_virtual', models.BooleanField(default=False)),
                ('date_entered', models.DateField(default=datetime.datetime.now)),
                ('last_updated_date', models.DateField(auto_now=True, null=True)),
                ('last_updated_time', models.TimeField(auto_now=True, null=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_entered', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SshKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('public_key', models.TextField()),
                ('key_type', models.CharField(choices=[('rsa', 'RSA'), ('ed25519 ', 'ed25519 ')])),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('date_entered', models.DateField(default=datetime.datetime.now)),
                ('last_updated_date', models.DateField(auto_now=True, null=True)),
                ('last_updated_time', models.TimeField(auto_now=True, null=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssh_entered', to=settings.AUTH_USER_MODEL)),
                ('fk_device_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.manageddevice')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssh_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Server',
        ),
    ]
