# Generated by Django 4.2 on 2025-05-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_manageddevice_sshkeys_delete_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageddevice',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manageddevice',
            name='os',
            field=models.CharField(choices=[('Windows', 'Windows'), ('Linux', 'Linux'), ('MacOS', 'MacOS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sshkeys',
            name='key_type',
            field=models.CharField(choices=[('ed25519 ', 'ed25519 '), ('rsa', 'RSA')]),
        ),
    ]
