# Generated by Django 4.2 on 2025-05-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_alter_manageddevice_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageddevice',
            name='has_keys',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='manageddevice',
            name='os',
            field=models.CharField(choices=[('MacOS', 'MacOS'), ('Windows', 'Windows'), ('Linux', 'Linux')], max_length=20),
        ),
    ]
