# Generated by Django 4.2 on 2025-05-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_manageddevice_has_keys_alter_manageddevice_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageddevice',
            name='device_type',
            field=models.CharField(choices=[('server', 'Server'), ('pc', 'PC')], max_length=20),
        ),
        migrations.AlterField(
            model_name='manageddevice',
            name='os',
            field=models.CharField(choices=[('Linux', 'Linux'), ('MacOS', 'MacOS'), ('Windows', 'Windows')], max_length=20),
        ),
    ]
