# Generated by Django 4.2 on 2025-05-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_alter_manageddevice_device_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageddevice',
            name='device_type',
            field=models.CharField(choices=[('yubikey', 'YubiKey'), ('server', 'Server'), ('pc', 'PC')], max_length=20),
        ),
        migrations.AlterField(
            model_name='manageddevice',
            name='os',
            field=models.CharField(choices=[('MacOS', 'MacOS'), ('Linux', 'Linux'), ('Windows', 'Windows')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sshkeys',
            name='key_type',
            field=models.CharField(choices=[('ed25519 ', 'ed25519 '), ('rsa', 'RSA')]),
        ),
    ]
