# Generated by Django 4.2 on 2023-12-06 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_item_entered_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='entered_date',
            new_name='date_entered',
        ),
        migrations.RemoveField(
            model_name='item',
            name='entered_time',
        ),
    ]
