# Generated by Django 4.2 on 2023-12-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_rename_entered_date_item_date_entered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='purchase_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
