# Generated by Django 4.2 on 2023-12-06 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_rename_updated_date_item_last_updated_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='purchase_Date',
            new_name='purchase_date',
        ),
    ]
