# Generated by Django 4.2 on 2025-03-04 01:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0015_item_extra1_item_extra2_item_extra3_item_extra4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='value',
            new_name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='extra1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='extra2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='extra3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='extra4',
        ),
        migrations.RemoveField(
            model_name='item',
            name='extra5',
        ),
        migrations.AddField(
            model_name='item',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='extra',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='has_accessories',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='value_now',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.CreateModel(
            name='ItemAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('value_now', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('model_number', models.CharField(blank=True, max_length=50, null=True)),
                ('extra', models.JSONField(blank=True, default=dict, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_entered', models.DateField(default=datetime.datetime.now)),
                ('last_updated_date', models.DateField(auto_now=True, null=True)),
                ('last_updated_time', models.TimeField(auto_now=True, null=True)),
                ('Item', models.ForeignKey(blank=True, limit_choices_to={'has_accessories': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.item')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_Accessories', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
