# Generated by Django 4.2 on 2025-05-21 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_rename_item_itemaccessories_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_category',
            new_name='fk_category_id',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='condition',
            new_name='fk_condition_id',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='room',
            new_name='fk_room_id',
        ),
        migrations.RenameField(
            model_name='itemaccessories',
            old_name='item',
            new_name='fk_item_id',
        ),
    ]
