# Generated by Django 4.2 on 2025-12-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_item_fk_category_id_alter_item_fk_condition_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='box',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
