# Generated by Django 4.2 on 2025-12-07 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_subcategory_console'),
        ('catalog', '0020_item_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fk_console_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.console'),
        ),
    ]
