# Generated by Django 4.2 on 2025-12-08 00:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_subcategory_console'),
        ('catalog', '0021_item_fk_console_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NatashaCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_description', models.CharField(blank=True, max_length=200, null=True)),
                ('cib', models.BooleanField(default=False)),
                ('date_entered', models.DateField(default=datetime.datetime.now)),
                ('fk_console_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.console')),
            ],
        ),
    ]
