# Generated by Django 4.2 on 2025-12-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_natashacollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='natashacollection',
            name='selling',
            field=models.BooleanField(default=True),
        ),
    ]
