# Generated by Django 4.2 on 2025-12-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_natashacollection_selling'),
    ]

    operations = [
        migrations.AddField(
            model_name='natashacollection',
            name='sealed',
            field=models.BooleanField(default=False),
        ),
    ]
