# Generated by Django 4.2 on 2025-12-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_natashacollection_sealed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='natashacollection',
            old_name='fk_console_id',
            new_name='fk_category',
        ),
        migrations.AddField(
            model_name='natashacollection',
            name='model_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='natashacollection',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='natashacollection',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='natashacollection',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='natashacollection',
            name='value_now',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
