# Generated by Django 4.2 on 2025-12-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_rename_fk_console_id_natashacollection_fk_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='natashacollection',
            name='extra',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
