# Generated by Django 4.2 on 2025-12-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_natashacollection_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='natashacollection',
            name='box',
            field=models.BooleanField(default=False),
        ),
    ]
