# Generated by Django 4.2 on 2025-05-21 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiowatch', '0002_micmonitorconfig_cooldown'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miceventlog',
            old_name='machine_id',
            new_name='fk_machine_id',
        ),
        migrations.RenameField(
            model_name='micmonitorconfig',
            old_name='machine_id',
            new_name='fk_machine_id',
        ),
    ]
