# Generated by Django 4.2 on 2025-10-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_category_is_catalog_category_is_maint_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['app_label', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='condition',
            options={'ordering': ['app_label', 'name']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['app_label', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'app_label')},
        ),
        migrations.AlterUniqueTogether(
            name='condition',
            unique_together={('name', 'app_label')},
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('name', 'app_label')},
        ),
    ]
