# Generated by Django 4.2 on 2025-12-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_category_options_alter_condition_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categories',
                'db_table': 'subcategory',
                'ordering': ['app_label', 'name'],
                'abstract': False,
                'unique_together': {('name', 'app_label')},
            },
        ),
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Console',
                'verbose_name_plural': 'Consoles',
                'db_table': 'Console',
                'ordering': ['app_label', 'name'],
                'abstract': False,
                'unique_together': {('name', 'app_label')},
            },
        ),
    ]
