# Generated by Django 4.2 on 2025-12-30 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_subcategory_console'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLabel',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Category Label',
                'verbose_name_plural': 'Category Labels',
                'db_table': 'category_labels',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.categorylabel'),
        ),
    ]
