# Generated by Django 4.2 on 2025-05-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0002_taxyear_is_active_alter_writeoff_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxyear',
            options={'ordering': ['-year']},
        ),
        migrations.RemoveField(
            model_name='taxyear',
            name='id',
        ),
        migrations.AlterField(
            model_name='taxyear',
            name='year',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
