# Generated by Django 4.2 on 2026-01-11 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0005_category_rename_amount_writeoff_amount_payable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writeoff',
            name='category',
        ),
    ]
