# Generated by Django 4.2 on 2026-01-11 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0006_remove_writeoff_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WriteOff',
        ),
    ]
