# Generated by Django 4.2 on 2026-01-11 06:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_categorylabel_category_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxes', '0008_writeoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entered', models.DateField(default=datetime.datetime.now)),
                ('last_updated_date', models.DateField(auto_now=True, null=True)),
                ('last_updated_time', models.TimeField(auto_now=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('amount_payable', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payable')),
                ('amount_receivable', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Receivable')),
                ('date', models.DateField(auto_now=True)),
                ('tags', models.CharField(blank=True, help_text="Comma-separated tags like 'mileage, gas'", max_length=255)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_entered_by', to=settings.AUTH_USER_MODEL)),
                ('fk_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxes.business')),
                ('fk_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxes.category')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.file')),
                ('tax_year', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='taxes.taxyear')),
            ],
            options={
                'db_table': 'tax_ledger',
                'ordering': ['tax_year', 'description'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='WriteOff',
        ),
    ]
