# Generated by Django 4.2 on 2026-01-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0010_alter_ledger_amount_payable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='amount_receivable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Receivable'),
        ),
    ]
