# Generated by Django 4.2 on 2025-05-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageddevice',
            name='agent_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='manageddevice',
            name='cpu_cores',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manageddevice',
            name='disk_total_gb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='manageddevice',
            name='kernel_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manageddevice',
            name='last_checked',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='manageddevice',
            name='ram_total_mb',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
