# Generated by Django 4.2 on 2025-05-29 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('devices', '0002_manageddevice_agent_version_manageddevice_cpu_cores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageddevice',
            name='is_public_facing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manageddevice',
            name='needs_keys',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='DeviceAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth', to='devices.manageddevice')),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authtoken.token')),
            ],
        ),
    ]
