# Generated by Django 4.2 on 2025-05-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_manageddevice_is_public_facing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageddevice',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
