# Generated by Django 4.2 on 2025-05-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_can_login_user_discord_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='discord_user_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
