# Generated by Django 4.2 on 2025-05-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiowatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='micmonitorconfig',
            name='cooldown',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
    ]
