# Generated by Django 4.2 on 2025-05-28 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('audiowatch', '0003_rename_machine_id_miceventlog_fk_machine_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miceventlog',
            name='fk_machine_id',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'is_virtual': False}, on_delete=django.db.models.deletion.CASCADE, related_name='MicEventLog_fk', to='devices.manageddevice'),
        ),
        migrations.AlterField(
            model_name='micmonitorconfig',
            name='fk_machine_id',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'is_virtual': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MicMonitorConfig_fk', to='devices.manageddevice'),
        ),
    ]
