# Generated by Django 4.2 on 2025-05-26 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0003_alter_taxyear_options_remove_taxyear_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxyear',
            name='date_entered',
        ),
        migrations.RemoveField(
            model_name='taxyear',
            name='entered_by',
        ),
        migrations.RemoveField(
            model_name='taxyear',
            name='last_updated_by',
        ),
        migrations.RemoveField(
            model_name='taxyear',
            name='last_updated_date',
        ),
        migrations.RemoveField(
            model_name='taxyear',
            name='last_updated_time',
        ),
    ]
