# Generated by Django 4.2 on 2025-02-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dkim',
            name='report_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
