# Generated by Django 4.2 on 2025-05-21 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_mgt', '0003_dkim_is_processed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dkim_record',
            old_name='dkim_id',
            new_name='fk_dkim_id',
        ),
    ]
