# Generated by Django 4.2 on 2023-12-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_item_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
