# Generated by Django 4.2 on 2023-12-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_item_date_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='date_entered',
            new_name='entered_date',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='date_updated',
            new_name='updated_date',
        ),
        migrations.AddField(
            model_name='item',
            name='entered_time',
            field=models.TimeField(blank=True, default='11:21:32', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
