# Generated by Django 4.2 on 2023-12-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_date_entered_item_entered_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='entered_time',
            field=models.TimeField(blank=True, default='11:26:24', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
