# Generated by Django 4.2 on 2023-12-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_item_entered_time_alter_item_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='entered_time',
            field=models.TimeField(blank=True, default='11:40:20', null=True),
        ),
    ]
