# Generated by Django 4.2 on 2025-03-04 02:47

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_rename_value_item_purchase_price_remove_item_extra1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemaccessories',
            old_name='Item',
            new_name='item',
        ),
        migrations.AddField(
            model_name='itemaccessories',
            name='name',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='extra',
            field=models.JSONField(blank=True, default=catalog.models.get_json, null=True),
        ),
        migrations.AlterField(
            model_name='itemaccessories',
            name='extra',
            field=models.JSONField(blank=True, default=catalog.models.get_json, null=True),
        ),
    ]
