# Generated by Django 4.2 on 2025-05-26 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_category_options'),
        ('catalog', '0018_rename_item_category_item_fk_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='fk_category_id',
            field=models.ForeignKey(blank=True, limit_choices_to={'app_label': 'catalog'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='fk_condition_id',
            field=models.ForeignKey(blank=True, limit_choices_to={'app_label': 'catalog'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.condition'),
        ),
        migrations.AlterField(
            model_name='item',
            name='fk_room_id',
            field=models.ForeignKey(blank=True, limit_choices_to={'app_label': 'catalog'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.room'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
