# Generated by Django 4.2 on 2025-05-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageddevice',
            name='device_type',
            field=models.CharField(choices=[('pc', 'PC'), ('server', 'Server'), ('yubikey', 'YubiKey')], max_length=20),
        ),
        migrations.AlterField(
            model_name='manageddevice',
            name='os',
            field=models.CharField(choices=[('Linux', 'Linux'), ('MacOS', 'MacOS'), ('Windows', 'Windows')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sshkeys',
            name='key_type',
            field=models.CharField(choices=[('rsa', 'RSA'), ('ed25519 ', 'ed25519 ')]),
        ),
    ]
