# Generated by Django 4.2 on 2025-05-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_manageddevice_device_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageddevice',
            name='device_type',
            field=models.CharField(choices=[('server', 'Server'), ('pc', 'PC'), ('yubikey', 'YubiKey')], max_length=20),
        ),
        migrations.AlterField(
            model_name='manageddevice',
            name='os',
            field=models.CharField(choices=[('Windows', 'Windows'), ('Linux', 'Linux'), ('MacOS', 'MacOS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sshkeys',
            name='key_type',
            field=models.CharField(choices=[('rsa', 'RSA'), ('ed25519 ', 'ed25519 ')]),
        ),
    ]
