# Generated by Django 4.2 on 2025-05-21 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_manageddevice_fk_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverstatus',
            old_name='app',
            new_name='fk_app_id',
        ),
    ]
