# Generated by Django 4.2 on 2025-05-22 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_rename_app_serverstatus_fk_app_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manageddevice',
            old_name='fk_user',
            new_name='fk_user_id',
        ),
    ]
