# Generated by Django 4.2 on 2025-05-28 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_rename_fk_user_manageddevice_fk_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manageddevice',
            name='entered_by',
        ),
        migrations.RemoveField(
            model_name='manageddevice',
            name='fk_user_id',
        ),
        migrations.RemoveField(
            model_name='manageddevice',
            name='last_updated_by',
        ),
        migrations.RemoveField(
            model_name='sshkeys',
            name='entered_by',
        ),
        migrations.RemoveField(
            model_name='sshkeys',
            name='fk_device_id',
        ),
        migrations.RemoveField(
            model_name='sshkeys',
            name='last_updated_by',
        ),
    ]
